name: Test

on:
  workflow_run:
    workflows: ["Install"]
    branches: ["main"]
    types: 
      - completed

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: 3.8
            name: ubuntu_latest_Python_3_8
            continue-on-error: true
          - os: ubuntu-latest
            python-version: 3.9
            name: ubuntu_latest_Python_3_9
            continue-on-error: true
          - os: ubuntu-20.04
            python-version: 3.8
            name: ubuntu_20_04_Python_3_8
            continue-on-error: true
          - os: ubuntu-20.04
            python-version: 3.9
            name: ubuntu_20_04_Python_3_9
            continue-on-error: true
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - name: Install build dependencies
      run: sudo apt-get install -y build-essential gcc
    - name: install packages
      run: pip install -r requirements.txt
    - run: make test
    - name: run python script to create summary report
      run: python Codes/src/test_lib.py
    - name: run python script to create output graph
      run : python Codes/python_script/test_graph.py
    - name: Archive and Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ml_pipeline-artifacts
        path: ${{ github.workspace }}
        
    - name: Save to repository
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        echo GH_TOKEN: "${GH_TOKEN}"
        git config --global user.name 'github-actions'
        git config --local user.email "action@github.com"
        git add .
        git commit -m "Add results"
        git push

    - name: deploy
      run: make deploy

    - name: Build status badge
      uses: RubbaBoy/BYOB@v1.3.0
      with:
        NAME: ${{ matrix.name }}
        LABEL: ${{ matrix.name }}
        STATUS: ${{ job.status }}
        COLOR: ${{ job.status == 'success' && 'green' || job.status == 'failure' && 'red' || 'yellow' }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}